### ISSUE TITLE
[RELEASE] 98.,98,.98.,98

### ISSUE THREAD

**Issue by neonphog** [neonphog/test#9]
### Version

987.87.7.7.8

### Tasks

- [ ] confirm works reasonably in the field someplace

### Tasks

- [ ] confirm works reasonably in the field someplace: @
- [ ] confirm launcher build: @
- [ ] confirm with manual runs of a stress test app: @
- [ ] confirm scaffolding works: @neonphog
- [ ] confirm holonix branch `main-0.x`: @
- [ ] confirm any docs/updates ready to publish after release lands: @
